export const BUS_SEARCH_REQUEST = "BUS_SEARCH_REQUEST";
export const BUS_SEARCH_SUCCESS = "BUS_SEARCH_SUCCESS";
export const BUS_SEARCH_FAILURE = "BUS_SEARCH_FAILURE";

export const CLEAR_BUS_SEARCH_REDUCER = "CLEAR_BUS_SEARCH_REDUCER";
